### ISSUE TITLE
Panel and SplitPanel do not always render initially

### ISSUE THREAD

**Issue by fleming79** [jtpio/ipylab#129]
The example is running from recent WinPython distribution (Jupyterlab 4.0.4), but the same issue happens for me using a conda dev [environment](https://github.com/jtpio/ipylab#development) running on WSL. The JupyterLite example works correctly, but everywhere else I've tried this has similar behaviour to that shown below.

Running through `widgets.ipynb` from the examples folder code. The panels appear, but the contents do not show up.

![image](https://github.com/jtpio/ipylab/assets/1474668/fe72c914-dea2-4221-8b04-0e1d8bcef34b)

Dragging the panels about can make the contents appear.

![image](https://github.com/jtpio/ipylab/assets/1474668/3c7d68ef-1927-4929-baf4-c70ecbad6972)

**Comment by fleming79** [comment]
It looks like it may be related to JupyterV4.# as it displays correctly with V3.

**Comment by fleming79** [comment]
I think it might be related to the error  "Uncaught (in promise) TypeError: MathJax.Hub is undefined"

![image](https://github.com/jtpio/ipylab/assets/1474668/36c50384-443a-4c1f-9489-65ee4374d485)

Line 139:
![image](https://github.com/jtpio/ipylab/assets/1474668/ceed1a66-028f-401b-964d-b90b5dd55308)


Perhaps it is associated with subclassing Panel from Vbox and adding on the title (which probably uses Mathjax)?

Given my limited knowledge of Jupyter. A few possible options that might work:

- Subclass from `ipywidgets.DOMWidget`  (similar to what Anywidget [does](https://github.com/manzt/anywidget/blob/fdb61c3c1e4be31998e532b1948e2ed07addb19e/anywidget/widget.py#L22)) defining the view in ipylab instead of using the ipywidget view.
- Remove the feature in `title` that uses mathjax.
- Have ipywidgets include mathjax in the context where it is missing.

**Comment by fleming79** [comment]
It looks like JupyterLab 4 switched to MathJax3 (https://github.com/jupyterlab/jupyterlab/pull/13877).

Looking in the source for ipywidgets `ipywidgets/packages/controls/src/utils.ts` the function `typeset` hasn't been upgraded to work with MathJax3. [source here](https://github.com/jupyter-widgets/ipywidgets/blob/689bc46a14e81c83c97ff8534b4eda6dfa46f574/packages/controls/src/utils.ts#L16).
```
export function typeset(element: HTMLElement, text?: string): void {
  if (text !== void 0) {
    element.textContent = text;
  }
  if ((window as any).MathJax !== void 0) {
    MathJax!.Hub!.Queue(['Typeset', MathJax.Hub, element]);
  }
}
```

The mathJax upgrade notes [here](https://docs.mathjax.org/en/latest/upgrading/v2.html?highlight=MathJax.Hub#changes-in-the-mathjax-api) explain that `Mathjax.Hub` has" been removed entirely" which is why the error occurs.

**Comment by jtpio** [comment]
So maybe it should be fixed in ipywidgets directly?

**Comment by erkin98** [comment]
i thinks it;s related to CSS or layout, so if you set css through Layout it should do the work

**Comment by pierre-yv** [comment]
Hi, I am facing the same issue but I have no console error of any kind. I can add to all of this:

- When created, the div element corresponding to the panel has not height or width set, then it does not show.
- When moving it around it acquires it's sizing properties and displays properly
But there are caveats:
- The positioning is not right (part of the panel comes bellow the tabs)
  - I can see it get width and height but not `min-width`, `min-height`, top`, and `left`
- The panel is not styled as an active tab (blue line on top)

**Comment by brian-from-quantrocket** [comment]
I experienced this issue as well but worked around it by moving the Panel creation logic into a JupyterLab extension and only using ipylab to call a command to run the extension from a notebook.

```python
    app = JupyterFrontEnd()

    app.commands.execute('my-command', {
        'arg1': arg1,
        'arg2': arg2,
        'insertMode': 'tab-after',
    })
```

Since ipylab is [intended as a bridge between notebooks and the JupyterLab UI](https://github.com/jtpio/ipylab/issues/134#issuecomment-1839012128), this keeps the bridge as short as possible. 

It won't work for every use case (e.g. if you're using ipywidgets in your Panel).

**Comment by matthewturk** [comment]
This may be a dead issue now, but I was still seeing it and I was able to fix it with:

```python
view = w.children[0].children[1]

p = ipylab.Panel(children = [view])
p.layout.min_height = '100%'
p.layout.width = '100%'
app.shell.add(p, 'main')
```

This works for my particular use case, but may not for others.  I was finding that when using `'split-right'` it was placing the widgets on the far left side, with a very small width.  I assume there is some nested style or display issue going on, but I wasn't able to identify the origin.
